[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
mypy_path = "custom_components/yeelight_bt"
no_implicit_optional = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true
